# Generated by Django 3.2.8 on 2021-10-24 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='member_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=30)),
                ('intro', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('member_start', models.IntegerField(default=1)),
                ('member_end', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('body', models.TextField()),
                ('difficulty', models.IntegerField(default=0)),
                ('phnum', models.CharField(max_length=13)),
                ('image', models.FileField(null=True, upload_to='image/')),
                ('is_over', models.BooleanField()),
                ('study_member', models.ManyToManyField(related_name='study_member', through='study.member', to=settings.AUTH_USER_MODEL)),
                ('study_member_request', models.ManyToManyField(related_name='study_member_request', through='study.member_request', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='study.study')),
            ],
        ),
        migrations.CreateModel(
            name='notion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notions', to='study.study')),
            ],
        ),
        migrations.AddField(
            model_name='member_request',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.study'),
        ),
        migrations.AddField(
            model_name='member_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.study'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='study.study')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
