# Generated by Django 4.0.6 on 2022-07-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_daily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_request',
            name='study',
        ),
        migrations.RemoveField(
            model_name='member_request',
            name='user',
        ),
        migrations.RemoveField(
            model_name='study',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='study',
            name='is_over',
        ),
        migrations.RemoveField(
            model_name='study',
            name='member_end',
        ),
        migrations.RemoveField(
            model_name='study',
            name='member_start',
        ),
        migrations.RemoveField(
            model_name='study',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='study',
            name='section',
        ),
        migrations.RemoveField(
            model_name='study',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='study',
            name='study_member',
        ),
        migrations.RemoveField(
            model_name='study',
            name='study_member_request',
        ),
        migrations.DeleteModel(
            name='member',
        ),
        migrations.DeleteModel(
            name='member_request',
        ),
    ]
