# Generated by Django 3.2.8 on 2021-10-24 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('bio', models.TextField(max_length=20, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('followings', models.ManyToManyField(related_name='followers', to='mypage.Profile')),
            ],
        ),
    ]
